image: docker:20.10

services:
  - docker:dind

stages:
  - deploy

variables:
  DOCKER_IMAGE_NAME: "vedu-client"
  DEPLOY_PATH: "/vedu"
  NETWORK: "vedu"

before_script:
  - mkdir -p ~/.ssh
  - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - ssh-keyscan -H $SERVER_HOST >> ~/.ssh/known_hosts

deploy_to_server:
  stage: deploy
  only:
    - master                     
  script:
    - cat "$ENV_FILE" > .env

    - cat .env

    - docker build -t $DOCKER_IMAGE_NAME .

    - docker save $DOCKER_IMAGE_NAME | gzip > $DOCKER_IMAGE_NAME.tar.gz

    - ssh root@$SERVER_HOST "echo Hello"

    - ssh root@$SERVER_HOST "mkdir -p $DEPLOY_PATH"

    - scp -o StrictHostKeyChecking=no $DOCKER_IMAGE_NAME.tar.gz root@$SERVER_HOST:$DEPLOY_PATH/

    - |
      ssh root@$SERVER_HOST "
      cd $DEPLOY_PATH &&
      docker stop $DOCKER_IMAGE_NAME || true &&
      docker rm $DOCKER_IMAGE_NAME || true &&
      docker rmi $DOCKER_IMAGE_NAME || true &&
      gunzip -c $DOCKER_IMAGE_NAME.tar.gz | docker load &&
      docker network inspect $NETWORK >/dev/null 2>&1 || docker network create $NETWORK &&
      docker run -d --name $DOCKER_IMAGE_NAME --network $NETWORK --restart always -p 8080:3000 $DOCKER_IMAGE_NAME
      "
  environment:
    name: production           
    url: http://$SERVER_HOST      