<template>
    <svg
        xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
        style="margin: auto; background: rgb(255, 255, 255); display: block; shape-rendering: auto;"
        :width="size"
        :height="size"
        viewBox="0 0 100 100"
        preserveAspectRatio="xMidYMid"
        :stroke="color"
    >
        <circle cx="50" cy="50" fill="none" stroke="inherit" :stroke-width="stroke" r="35"
                stroke-dasharray="164.93361431346415 56.97787143782138">
            <animateTransform attributeName="transform" type="rotate" repeatCount="indefinite" dur="1s"
                              values="0 50 50;360 50 50" keyTimes="0;1"></animateTransform>
        </circle>
        <!-- [ldio] generated by https://loading.io/ --></svg>
</template>

<script setup lang="ts">
import { useSize } from "~/ui/composables/useSize";
import { useColor } from "~/ui/composables/useColor";

export interface Props {
    size?: string | number,
    color?: string,
    stroke?: number
}

const props = withDefaults(defineProps<Props>(), {
    size: 24,
    color: 'primary-700',
    stroke: 8
})

const { size } = useSize(props.size)
const { color } = useColor(props.color)

</script>


<style scoped>

</style>